version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    commit-message:
      prefix: "chore(pnpm): "
    labels:
      - "ðŸ”„ update"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    commit-message:
      prefix: "chore(docker): "
    labels:
      - "ðŸ”„ update"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    assignees:
      - "nicokempe"
    commit-message:
      prefix: "chore(actions): "
    labels:
      - "ðŸ”„ update"
